INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (1, 'Bông cải xanh luộc ', 25.5, '40000',  '1.5kg bông cải xanh', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (2, 'Cà rốt luộc ', 20.5, '30000',  '1.5kg cà rốt', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (3, 'Cải bắp xào ', 33, '40000',  '1.5kg cải bắp, 200g tỏi', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (4, 'Canh bầu nấu tôm ', 25, '120000',  '1.5kg bầu, 100g tôm khô', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (5, 'Canh bí đỏ ', 19.5, '40000',  '1.5kg bí đỏ', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (6, 'Canh cải bắp ', 21.5, '40000',  '1.5kg cải bắp, 100g gừng', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (7, 'Canh mùng tơi nấu cua ', 23.5, '50000',  '1.5kg mùng tơi, 200g cua đồng', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (8, 'Canh rau cải xanh ', 23, '40000',  '1.5kg rau cải xanh', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (9, 'Canh rau muống ', 22.5, '20000',  '1.5kg rau muống', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (10, 'Canh rau ngót ', 26, '50000',  '1.5kg rau ngót', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (11, 'Canh su hào ', 20, '20000',  '1.5kg su hào', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (12, 'Đậu cô ve luộc ', 23, '50000',  '1.5kg đậu cô ve', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (13, 'Đậu cô ve xào tỏi ', 38, '60000',  '1.5kg đậu cô ve, 10g tỏi', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (14, 'Ớt chuông luộc ', 22.5, '30000',  '1kg ớt chuông', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (15, 'Rau cải xanh xào ', 38, '50000',  '1.5kg rau cải xanh, 200g tỏi', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (16, 'Rau muống xào tỏi ', 37.5, '50000',  '1kg rau muống, 200g tỏi', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (17, 'Salad dưa chuột cà chua ', 21, '30000',  '1kg dưa chuột, 1kg cà chua', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (18, 'Súp lơ trắng luộc ', 19, '60000',  '1.5kg súp lơ trắng', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (19, 'Canh rau bí ', 15, '50000',  '1.5kg rau bí', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (20, 'Rau bí xào tỏi', 30, '60000',  '1.5kg rau bí, 200g tỏi', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (21, 'Giá đỗ xào ', 34, '50000',  '1.5kg giá đỗ', 'fiber');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (22, 'Cá quả nướng ', 73, '120000',  '1.5kg cá quả', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (23, 'Cá quả sốt cà chua ', 82, '130000',  '1.5kg cá quả, 1kg cà chua', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (24, 'Cá thu sốt cà chua ', 99, '140000',  '1kg cá thu, 1kg cà chua', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (25, 'Chả lá lốt ', 138.5, '130000',  '1kg thịt heo, 150g lá lốt', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (26, 'Chả lụa ', 69, '120000',  '0.6kg chả lụa', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (27, 'Đậu kho ', 66, '80000',  '1kg đậu phụ, 500ml nước cốt dừa', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (28, 'Đậu phụ sốt cà chua ', 59, '60000',  '1kg đậu phụ, 1kg cà chua', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (29, 'Mực rim me ', 87, '230000',  '1kg mực, 500g me', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (30, 'Mực xào hành tây ', 86, '220000',  '1kg mực, 1kg hành tây', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (31, 'Thịt bò hầm nước cốt dừa ', 175, '290000',  '1kg bò II, 500ml nước cốt dừa', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (32, 'Thịt bò xào ớt chuông ', 165, '280000',  '1kg bò II, 1kg ớt chuông', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (33, 'Thịt bò xay nướng ', 144, '220000',  '1kg bò I', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (34, 'Thịt bò xay rang hành ', 152, '230000',  '1kg bò I, 400g hành củ', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (35, 'Thịt bò xay viên sốt cà chua ', 153, '230000',  '1kg bò I, 1kg cà chua', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (36, 'Thịt gà nướng mật ong ', 176.5, '200000',  '1.5kg gà, 200g mật ong', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (37, 'Thịt gà quay ', 146, '120000',  '1.5kg gà', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (38, 'Thịt gà rang gừng ', 162, '140000',  '1.5kg gà, 400g gừng', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (39, 'Thịt gà tần ', 146, '120000',  '1.5kg gà', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (40, 'Thịt heo kho ', 135.5, '110000',  '1kg thịt heo', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (41, 'Thịt heo rang hành ', 143.5, '120000',  '1kg thịt heo, 400g hành củ', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (42, 'Thịt heo xay sốt cà chua ', 144.5, '120000',  '1kg thịt heo, 1kg cà chua', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (43, 'Tôm thẻ hấp ', 64.5, '150000',  '1.5kg tôm thẻ', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (44, 'Tôm thẻ sốt chua ngọt ', 73.5, '160000',  '1.5kg tôm thẻ, 1kg cà chua', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (45, 'Trứng gà rán ', 73.5, '60000',  '1kg trứng rán', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (46, 'Trứng hấp nấm ', 93, '160000',  '1kg trứng gà, 1kg nấm', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (47, 'Chả bò ', 74, '170000',  '0.6kg chả bò', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (48, 'Chả quế ', 116, '110000',  '0.6kg chả quế', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (49, 'Trứng sốt cà chua ', 82.5, '70000',  '1k trứng gà, 1kg cà chua', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (50, 'Thịt heo rang nấm ', 153, '210000',  '1kg thịt heo, 1kg nấm', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (51, 'Lươn hấp ', 140.5, '200000',  '1kg lươn', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (52, 'Thịt bò xào bông cải xanh ', 167, '290000',  '1kg bò II, 1kg bông cải xanh', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (53, 'Thịt bò xào cà tím ', 169, '280000',  '1kg bò II, 1kg cà tím', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (54, 'Thịt gà xào nấm ', 163.5, '220000',  '1.5kg gà, 1kg nấm', 'protein');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (55, 'Bún tươi ', 137.5, '40000',  '2.5kg bún', 'carb');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (56, 'Cơm gạo lứt ', 137.5, '60000',  '2.5kg cơm gạo lứt', 'carb');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (57, 'Cơm trắng ', 162.5, '60000',  '2.5kg cơm', 'carb');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (58, 'Phở ', 150, '40000',  '2.5kg bánh phở', 'carb');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (59, 'Cháo ', 75, '40000',  '3kg cháo', 'carb');
INSERT INTO `meals`.`mon_an` (`id`, `ten_mon_an`, `gia_tri_dinh_duong`, `gia_tien`, `mo_ta`, `phan_loai`) VALUES (60, 'Bánh đa ', 179, '60000',  '2.5kg bánh đa', 'carb');